#/etc/needrestart/conf.d/custom_restarts.conf

# --- SERVICIOS QUE ES MEJOR REINICIAR AUTOMÁTICAMENTE (Valor = 1) ---
# Servicios del sistema seguros o herramientas de optimización
$nrconf{override_rc}{qr(^auto-cpufreq)} = 1;
$nrconf{override_rc}{qr(^firewalld)} = 1;
$nrconf{override_rc}{qr(^systemd-timesyncd)} = 1;
$nrconf{override_rc}{qr(^upower)} = 1;

# --- SERVICIOS CRÍTICOS QUE ES MEJOR IGNORAR/REINICIAR MANUALMENTE (Valor = 0) ---
# Reiniciar el entorno gráfico (sddm) o el gestor de logeo cerrará tu sesión activa de golpe
$nrconf{override_rc}{qr(^sddm)} = 0;
$nrconf{override_rc}{qr(^systemd-logind)} = 0;

# Desconectarte de la red en medio de una actualización puede romper descargas o conexiones SSH
$nrconf{override_rc}{qr(^NetworkManager)} = 0;
$nrconf{override_rc}{qr(^proton\.VPN)} = 0;
$nrconf{override_rc}{qr(^wpa_supplicant)} = 0;

# Otros componentes internos de systemd que prefieras manejar con cuidado
$nrconf{override_rc}{qr(^systemd-manager)} = 0;
$nrconf{override_rc}{qr(^systemd-journald)} = 0;
$nrconf{override_rc}{qr(^systemd-udevd)} = 0;
$nrconf{override_rc}{qr(^systemd-userdbd)} = 0;
