address_family = both
capture = portal
csrf_allowed_origins = https://100.68.214.102:47990,https://gamer-linux:47990,https://gamer-linux.tale-arctic.ts.net:47990
fec_percentage = 10
lan_encryption_mode = 1
min_threads = 4
minimum_fps_target = 60
nvenc_latency_over_power = high
nvenc_preset = 1
nvenc_twopass = disabled
output_name = virtual-fallback-display
sunshine_name = Gamer-Linux
vk_rc_mode = 0
wan_encryption_mode = 2
