monitor.alsa.rules = [
  {
    matches = [
      {
        -- Esto aplica a cualquier nodo que sea una salida de audio
        "node.name" = "~alsa_output.*"
      }
    ]
    actions = {
      update-props = {
        -- Aumentamos el headroom (por defecto suele ser 0 o muy bajo)
        "api.alsa.headroom" = 1024
        -- Opcional: Desactivar la suspension si el audio se corta al estar en silencio
        "session.suspend-timeout-seconds" = 0
      }
    }
  }
]
