[preferred]
# Usar GTK para elegir archivos (se ve bonito)
org.freedesktop.impl.portal.FileChooser=gtk

# Usar WLR (Sway) para capturar la pantalla/ventanas
org.freedesktop.impl.portal.ScreenCast=wlr

# Para capturas de pantalla estáticas
org.freedesktop.impl.portal.Screenshot=wlr

# Fallback para todo lo demás
default=gtk
