device {
    name = logitech-usb-keyboard
    kb_layout = es
}

# laptop Dell Latitude 7430 
device {
    name = at-translated-set-2-keyboard
    kb_layout = us
}

# Sunshine keyboard
device {
    name = keyboard-passthrough
    kb_layout = es
}

device {
    name = wireless-controller-touchpad
    enabled = false
}
