general {
    # Comando para bloquear cuando llegue el momento
    lock_cmd = pidof hyprlock || hyprlock
    
    # Si suspende el PC manualmente (tapa cerrada), bloquear siempre antes
    before_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action="on"})'
 && loginctl lock-session
    
    # Al volver, encender pantalla
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action="on"})'
}

# Apagar pantalla por inactividad
listener {
    timeout = 300
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({action="off"})' # Apaga el monitor
    on-resume = hyprctl dispatch 'hl.dsp.dpms({action="on"})'
}

# Bloquear sesion 5 min después de apagar
listener {
    timeout = 360                          # 60s (apagar) + 300s (5 min de espera)
    on-timeout = loginctl lock-session     # Ahora sí, pone el candado
}

# Apagar luego de 1 min si se bloquea manualmente
listener {
    timeout = 60
    ignore_inhibit= true
    on-timeout = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms({action="off"})' # Apaga el monitor si esta bloqueado
    on-resume = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms({action="on"})'
}

# Desconectar DS4 plateado
listener {
    timeout = 600
    ignore_inhibit= true
    on-timeout = bluetoothctl disconnect "40:1B:5F:3E:98:C0"
}
