general {
    # Comando para bloquear cuando llegue el momento
    lock_cmd = pidof hyprlock || hyprlock
    
    # Si suspende el PC manualmente (tapa cerrada), bloquear siempre antes
    before_sleep_cmd = loginctl lock-session
    
    # Al volver, encender pantalla
    after_sleep_cmd = hyprctl dispatch dpms on
}

# --- LISTENER 1: APAGAR PANTALLA (Primero) ---
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off # Apaga el monitor
    on-resume = hyprctl dispatch dpms on   # Lo enciende si vuelves
}

# --- LISTENER 2: BLOQUEAR (5 min después de apagar) ---
listener {
    timeout = 360                          # 60s (apagar) + 300s (5 min de espera)
    on-timeout = loginctl lock-session     # Ahora sí, pone el candado
}

# Listener para cuando se cierra la tapa
listener {
    event = sw_on:Lid Switch  # Detecta el cierre
    on-status-changed = hyprctl dispatch dpms off  # Apaga la pantalla
}

# Listener para cuando se abre la tapa
listener {
    event = sw_off:Lid Switch # Detecta la apertura
    on-status-changed = hyprctl dispatch dpms on   # Enciende la pantalla
}
