#preload = /usr/share/backgrounds/iron-man-red-glow-5120x2880-24338.png
preload = /home/stefano/wallhaven-8odody.jpg

#wallpaper {
#    monitor = DP-3 
#    #jpath = /usr/share/backgrounds/iron-man-red-glow-5120x2880-24338.png
#k    path = /home/stefano/wallhaven-8odody.jpg
#    fit_mode = cover
#}

wallpaper {
    monitor = 
    #path = /usr/share/backgrounds/iron-man-red-glow-5120x2880-24338.png
    path = /home/stefano/wallhaven-8odody.jpg
    fit_mode = cover
}

splash = false
#splash_offset = 20
#splash_opacity = 0.8
#ipc = true
