-- --- MONITORES ---
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

--monitorv2 {
--    output = HEADLESS-2
--    mode = 1920x1080@144
--    position = 0x0
--    #position = auto
--    scale = 1
--    vrr = 1
--    #bitdepth = 8
--    #bitdepth = 10
--    #cm = hdr
--}

-- Monitor principal para que sunshine pueda tener un stream constante
hl.monitor({
    output = "virtual-fallback-display",
    mode = "1920x1080@144",
    position = "0x0",
    --position = auto
    scale = "1",
    vrr = 1,
    --bitdepth = 8
    --bitdepth = 10
    --cm = hdr
})

-- gamer
hl.monitor({
    output = "desc:Acer Technologies Acer KG241 P 0x92638149",
    mirror = "virtual-fallback-display",
    mode = "1920x1080@144",
    scale = "1",
    bitdepth = 8,
    --cm = hdr,
    vrr = 1,
})

-- laptop-stefano
hl.monitor({
    output = "desc:AU Optronics 0x4A90",
    --mirror = HEADLESS-2,
    mirror = "virtual-fallback-display",
    mode = "1920x1080@60",
    scale = "1.2",
    bitdepth = 8,
    vrr = 1,
})

--monitorv2 { # HDMI laptop
--    output = HDMI-A-1
--    mirror = HEADLESS-2
--    position = auto
--    scale = 1
--    bitdepth = 8
--    vrr=1
--}

-- Pantalla tactil Raspberry
hl.monitor({
    output = "desc:Mediatrix Peripherals Inc MPI5001 0x00000001",
    mode = "1280x720@60",
    bitdepth = 8,
    scale = "1.6",
    position = "560x1080",
})

-- Configuracion por defecto
hl.monitor({
    output = "",
    disabled = true,
})

--monitor=,preferred,auto,1

require("monitors_presentation")

-- Hace que algunas apps con datos posiblemente sensibles no se vean al compartir pantalla
streamer_mode = false

-- --- PROGRAMAS ---
terminal = "alacritty"
fileManager = "dolphin"

-- comandos
--$menu = wofi --show drun
--$menu = rofi -show drun
menu = "~/.config/hypr/scripts/rofi_launcher.sh"
screenshot = "grim -g \"$(slurp)\" - | swappy -f -"
poweroff = "hyprshutdown --post-cmd \"systemctl poweroff\""
reboot = "hyprshutdown --post-cmd \"systemctl reboot\""
logout = "hyprshutdown"
--$browser= uwsm app -- brave-browser.desktop
browser = "uwsm app -- com.brave.Origin.beta.desktop"

-- --- AUTOSTART ---
--# para uwsm usar el comando para los programas: uwsm app -- [comando]
--exec = echo $HYPRLAND_INSTANSE_SIGNATURE > /home/stefano/.cache/hyprsignature.txt

-- inhibir el boton de inicio

-- --- APPS DE SISTEMA ---
--exec-once = uwsm app -- /usr/lib/pam_kwallet_init
--exec-once = uwsm app -- xembedsniproxy
--exec-once = uwsm app -- dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

-- Replay buffer de obs
--exec-once = uwsm app -- obs --minimize-to-tray --startreplaybuffer --scene Replay

-- exec-once = /home/stefano/proyectos/ProyectoAutoCambiadorPerfiles/clanker

-- --- PORTAPAPELES (CLIPBOARD) ---
-- 1. Borrar historial anterior al reiniciar

-- Iniciar servicios de copiado

-- Plugins

-- --- PERMISOS ---
hl.permission({ binary = "/usr/bin/hyprlock", type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/(bin|local/bin)/hyprpm", type = "plugin", mode = "allow" })


-- Layouts
--workspace = 1, layout:master

hl.env("GDK_SCALE", "1")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 7,
    bezier = "myBezier",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 7,
    bezier = "default",
    style = "popin 80%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 8,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 7,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6,
    bezier = "default",
})
hl.animation({
    leaf = "layers",
    enabled = false,
})

-- Source: ~/.config/hypr/devices.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("devices")

-- Source: ~/.config/hypr/binds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("binds")

-- Source: ~/.config/hypr/layerrules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("layerrules")

-- Source: ~/.config/hypr/windowrules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("windowrules")

-- Source: ~/.config/hypr/monitors_sunshine.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("monitors_sunshine")

-- TODO: manual review — plugin section ''. The new Lua API exposes plugins via hl.plugin.<name>(...) — wire up per the plugin's docs.
--[[
  hyprbars { ... }
  --    hyprexpo {
  --        columns = 3
  --        gap_size = 5
  --        bg_col = rgb(111111)
  --        workspace_method = center current
  --
  --        gesture_distance = 300
  --    }
  hy3 { ... }
]]

hl.config({
    group = {
        insert_after_current = true,
        col = {
            border_active = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            border_inactive = "rgba(595959aa)",
        },
        groupbar = {
            font_size = 10,
            gradients = true,
            render_titles = true,
            col = {
                active = "rgba(33ccffee)",
                inactive = "rgba(595959aa)",
            },
        },
    },
    -- --- VARIABLES DE ENTORNO ---
    -- --- VARIABLES DE UI EN HYPRLAND.CONF ---
    misc = {
        --vfr = true
        vrr = true,
        render_unfocused_fps = 30,
	disable_autoreload = false
    },
    xwayland = {
        force_zero_scaling = true,
        use_nearest_neighbor = true,
    },
    ecosystem = {
        --enforce_permissions = true
        enforce_permissions = false,
    },
    -- --- INPUT ---
    input = {
        kb_layout = "latam",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        numlock_by_default = true,
        follow_mouse = 1,
        touchpad = {
            natural_scroll = true,
            disable_while_typing = false,
            clickfinger_behavior = true,
            drag_lock = true,
            scroll_factor = 0.15,
        },
        sensitivity = 0,
        -- El retraso antes de empezar a repetir (en milisegundos)
        repeat_delay = 200,
        -- La velocidad de repetición (caracteres por segundo)
        repeat_rate = 45,
    },
    -- --- APARIENCIA ---
    general = {
        gaps_in = 2,
        gaps_out = 5,
        border_size = 0,
        col = {
            active_border = "rgb(d05d0e)",
            inactive_border = "rgb(181825)",
        },
        layout = "dwindle",
        allow_tearing = true,
    },
    render = {
        direct_scanout = false, -- A veces true causa artefactos en desktop
    },
    debug = {
        damage_tracking = 1, -- 2 es el valor por defecto y más estable
        disable_logs = true,
    },
    -- Opciones experimentales para Nvidia
    cursor = {
        no_hardware_cursors = true,
    },
    decoration = {
        rounding = 3,
        active_opacity = 1.0,
        inactive_opacity = 0.8,
        -- SINTAXIS NUEVA (Shadow)
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
        },
    },
    -- --- ANIMACIONES ---
    animations = {
        enabled = false,
    },
    -- --- LAYOUTS ---
    dwindle = {
        preserve_split = true,
    },
    -- --- GESTURES (ELIMINADO) ---
    -- La sección "gestures" con "workspace_swipe" causaba error porque fue eliminada.
    -- Si necesitas gestos, ahora se configuran de otra forma en la wiki oficial.
    -- --- DISPOSITIVOS ---
    -- --- ATAJOS DE TECLADO ---
    -- -- LAYERRULES ---
    -- REGLAS DE VENTANA
    -- sunshine conf
})

hl.on("hyprland.start", function()
    hl.exec_cmd("~/.scripts/sunshine_desk_deactivate.sh")
    hl.exec_cmd("uwsm app -- systemd-inhibit --what=handle-power-key:handle-reboot-key:handle-lid-switch --who=\"Hyprland Session\" --why=\"Custom shutdown/lid handling\" --mode=block Hyprland")
    hl.exec_cmd("uwsm app -- kdeconnect-indicator")
    hl.exec_cmd("uwsm app -- swayosd-server")
    hl.exec_cmd("rm \"$HOME/.cache/cliphist/db\"")
    hl.exec_cmd("uwsm app -- wl-paste --type text --watch cliphist store")
    hl.exec_cmd("uwsm app -- wl-paste --type image --watch cliphist store")
    hl.exec_cmd("hyprpm reload -n")
end)

hl.config({
    plugin = {
        hyprcapture = {
            default_mode = "region",
            fullscreen_scope = "all",
            window_background = "follow-system",
            window_border = "keep",
            window_shadow = "keep",
            save = true,
            clipboard = true,
            show_thumbnail = true,
            allow_quick = false,
            confirm_before_capture = false,
            fusion_mode = false,
            save_dir = "$XDG_PICTURES_DIR/Screenshots",
            filename_template = "Screenshot-%Y-%m-%d-%H%M%S.png",
            record_save_dir = "$XDG_VIDEOS_DIR/Screenrecords",
            record_filename_template = "Recording-%Y-%m-%d-%H%M%S.mp4",
            record_format = "mp4",
            record_transparent_format = "webm",
            record_fps = 30,
            record_fps_options = "15 24 30 60",
            record_window_fps_limit = 12,
            record_window_real_bg_fps_limit = 8,
            record_codec = "libx264",
            record_transparent_codec = "auto",
            record_solid_alpha = false,
            record_preset = "veryfast",
            record_gsr_flags = "",
            record_window_backend = "compositor",
            record_max_seconds = 0,
            record_countdown_seconds = 0,
            include_cursor = false,
            thumbnail_timeout_ms = 5000,
            watermark = "",
            watermark_position = "central",
            watermark_width = "20%",
            watermark_offset = "0 0",
        },
    },
})
