# --- Configuración de Colores ---
# Background color.
background = 0xFF181825

# Base color.
base = 0xFF1E1E2E

# Text color.
text = 0xFFCDD6F4

# Alternative base color.
alternate_base = 0xFF313244

# Bright text color.
bright_text = 0xFFF5E0DC

# Accent color.
accent = 0xFFFAB387

# Secondary accent color.
accent_secondary = 0xFFD65D0E


# --- Configuración de Tipografía y Tamaños ---
# Font size for H1.
h1_size = 19

# Font size for H2.
h2_size = 15

# Font size for H3.
h3_size = 13

# Font size for regular text elements.
font_size = 11

# Font size for small text elements.
small_font_size = 10

# Name of the font family to use.
font_family = "Sans Serif"

# Name of the monospace font family to use.
font_family_monospace = "monospace"


# --- Interfaz e Iconos ---
# Name of the icon theme to use, empty for “the first found”.
icon_theme = ""

# Big rounding in logical px
rounding_large = 10

# Small rounding in logical px
rounding_small = 5
