default {
    timeout = unlimited;
    layer = 5;
}

layer_1 {
    cursor_ide {
        cmdline = "/usr/lib/electron40/electron /usr/share/cursor/resources/app/cursor.mjs";
	timeout = unlimited;
    }
    alacritty {
        path = "/usr/bin/alacritty";
	timeout = unlimited;
    }
    tmux {
        path = "/usr/bin/tmux";
	timeout = unlimited;
    }
}

layer_0 {
    hyprpaper {
        path = "/usr/bin/hyprpaper";
        timeout = 3;
    }
    swayosd_server {
        path = "/usr/bin/swayosd-server";
        timeout = 3;
    }
    opensnitch_ui {
        cmdline = "/usr/bin/python /usr/bin/opensnitch-ui";
        timeout = 3;
	#hidden = true;
    }
    xwaylandvideobridge {
        path = "/usr/bin/xwaylandvideobridge";
        timeout = 3;
    }
    wl_paste {
        path = "/usr/bin/wl-paste";
        timeout = 3;
    }
    waybar {
        path = "/usr/bin/waybar";
        timeout = 3;
    }
    xembedproxy {
        path = "/usr/bin/xembedsniproxy";
        timeout = 3;
    }
    systemd_inhibit {
        path = "/usr/bin/systemd-inhibit";
        timeout = 3;
    }
    kdeconnect_indicator {
        path = "/usr/bin/kdeconnect-indicator";
        timeout = 3;
    }
}
