-- =========================================================  
-- 🪟 REGLAS DE VENTANA (SINTAXIS DE BLOQUES ESTRICTA)  
-- =========================================================  

-- Suprimir eventos de maximizado (ayuda con apps de QT/GTK)  
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    name = "suppress-maximize",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- >> STEAM (Ventanas de propiedades de juegos)
hl.window_rule({
    name = "steam-games-properties",
    match = {
        class = "^(steam)$",
    },
    float = true,
    center = true,
})

-- >> STEAM (Ventanas Secundarias/Popups)
hl.window_rule({
    name = "steam-popups",
    match = {
        class = "^(steam)$",
        title = "^(Sign in to Steam|Friends List|Steam Settings|Create or select.*|Sign in to Steam|Special Offers)$",
    },
    float = true,
    center = true,
})

-- >> STEAM (Arreglo de Menús y Tooltips)  
-- Fix crítico para menús que parpadean o aparecen vacíos  
hl.window_rule({
    name = "steam-menus-fix",
    match = {
        class = "^(steam)$",
        title = "^$",
    },
    stay_focused = true,
    min_size = {1, 1},
})

-- >> LANZADORES (Lutris, Heroic)  
-- Al Workspace 5 junto con Steam  

-- --- 3. NAVEGACIÓN Y WEB APPS ---  
local braveClass= "^(brave-browser|brave-origin-beta|Brave-origin-beta)$"

hl.window_rule({
    name = "brave-browser",
    match = {
        class = braveClass,
    },
    --match:class = ^(brave-browser)$
    no_blur = true,
    opacity = "1 override 1 override",
    border_color = "rgb(d05d0e)",
})

-- >> BRAVE (Principal)  
hl.window_rule({
    name = "brave-browser-principal",
    match = {
        class = braveClass,
        title = "^(Principal)$",
    },
    --match:class = ^(brave-browser)$
    --maximize = true
    no_blur = true,
    workspace = "1",
    float = false,
    border_color = "rgb(d05d0e)",
})

-- --- 4. UTILIDADES FLOTANTES ---  

-- Grupo de Apps que siempre deben flotar y centrarse  
hl.window_rule({
    name = "floating-utils",
    match = {
        class = "^(org.gnome.Nautilus|thunar|org.pulseaudio.pavucontrol|blueman-manager|nm-connection-editor)$",
    },
    float = true,
    center = true,
})

-- Tamaños específicos para Gestor de Archivos  
hl.window_rule({
    name = "FileManager",
    match = {
        class = "^(org.gnome.Nautilus|thunar)$",
    },
    size = "1000 800",
    center = true,
})

-- Tamaños específicos para Control de Volumen  
hl.window_rule({
    name = "pavucontrol-size",
    match = {
        class = "^(org.pulseaudio.pavucontrol)$",
    },
    size = "800 500",
})

-- --- 5. COMPATIBILIDAD (XWayland Video Bridge) ---  
-- Necesario para compartir pantalla en Discord/Zoom  
hl.window_rule({
    name = "xwayland-videobridge",
    match = {
        class = "^(xwaylandvideobridge)$",
    },
    opacity = "0.0 override 0.0 override",
    no_anim = true,
    no_initial_focus = true,
    max_size = "1 1",
    no_blur = true,
})

hl.window_rule({
    name = "dolphin-main",
    match = {
        class = "^(org.kde.dolphin)$",
        initial_title = "^(.* — Dolphin)$",
    },
    float = true,
    center = true,
    --size = 1200 800
    size = "monitor_w*0.84 monitor_h*0.84",
})

hl.window_rule({
    name = "dolphin-process-dialog",
    match = {
        class = "^(org.kde.dolphin)$",
        initial_title = "^(Progress Dialog.*)$",
    },
    float = true,
    center = true,
})

hl.window_rule({
    name = "dolphin-properties",
    match = {
        class = "^(org.kde.dolphin)$",
        initial_title = "^(Properties for.*)$",
    },
    float = true,
    center = true,
})

hl.window_rule({
    name = "guardado-de-archivos-portal",
    match = {
        class = "^(org.freedesktop.impl.portal.desktop.kde)$",
    },
    float = true,
    center = true,
    size = "monitor_w*0.84 monitor_h*0.84",
})

hl.window_rule({
    name = "Print",
    match = {
        initial_title = "^(Print)$",
    },
    float = true,
})

hl.window_rule({
    name = "Qalculate",
    match = {
        class = "^(qalculate-gtk)",
    },
    float = true,
    size = "782 539",
})

hl.window_rule({
    name = "Terminal",
    match = {
        class = "^(Alacritty)",
    },
    float = false,
    size = "1167, 793",
})

hl.window_rule({
    name = "PacketTracerOther",
    match = {
        class = "^(PacketTracer)",
    },
    opacity = "1.0 override 1.0 override",
    stay_focused = false,
    float = true,
})

hl.window_rule({
    name = "PacketTracerOther-2",
    match = {
        class = "^(PacketTracer)",
        title = "^(Error)",
    },
    opacity = "1.0 override 1.0 override",
    stay_focused = false,
    float = true,
})

-- PacketTracer WindowRules

-- Global for PacketTracer
hl.window_rule({
    name = "PacketTracer",
    match = {
        class = "^(PacketTracer)",
    },
    -- Fix drag and drop on XWayland
    no_initial_focus = true,
    float = true,
    no_anim = true,
    no_blur = true,
    no_dim = true,
    no_shadow = true,
    opaque = true,
    immediate = true,
    border_size = 0,
    rounding = 0,
    decorate = false,
    nearest_neighbor = true,
    xray = true,
    min_size = {1,1},
    keep_aspect_ratio = true,
})

hl.window_rule({
    name = "PacketTracer2",
    match = {
        class = "^(PacketTracer)",
        title = "^(Cisco Packet Tracer)",
    },
    keep_aspect_ratio = true,
    focus_on_activate = true,
})

hl.window_rule({
    name = "PacketTracer3",
    match = {
        class = "^(PacketTracer)",
        title = "^(Preference)",
    },
    min_size = "486 628",
    --stayfocused = on
})

hl.window_rule({
    name = "PacketTracer4",
    match = {
        class = "^(PacketTracer)",
        title = "^(.*outer.*)",
    },
    min_size = "486 628",
})

hl.window_rule({
    name = "PacketTracer5",
    match = {
        class = "^(PacketTracer)",
        title = "^(.*witch.*)",
    },
    min_size = "486 628",
})

hl.window_rule({
    name = "PacketTracer5",
    match = {
        class = "^(PacketTracer)",
        title = "^(.*PC.*)",
    },
    min_size = "772 700",
})

hl.window_rule({
    name = "PacketTracer6",
    match = {
        class = "^(PacketTracer)",
        title = "^(.*Save File.*)",
    },
    min_size = "807 655",
})

hl.window_rule({
    name = "Discord-Main",
    match = {
        class = "^(discord)",
    },
    opacity = "1.0 override 1.0 override",
})

hl.window_rule({
    name = "Discord-PopUp",
    match = {
        class = "^(discord)",
        initial_title = "^(Discord Popout)",
    },
    opacity = "1.0 override 1.0 override",
    float = true,
})

hl.window_rule({
    name = "workspace1",
    match = {
        workspace = 1,
    },
    -- debe estar por encima de reglas que muevan las ventanas a otros workspaces
    -- por debajo de todas las demas
    float = true,
    size = "80% 80%",
})

hl.window_rule({
    name = "workspace10",
    match = {
        workspace = 10,
    },
    opacity = "1 override 1 override",
    focus_on_activate = false,
})

-- >> DISCORD
hl.window_rule({
    name = "discord",
    match = {
        class = "^(discord)$",
    },
    workspace = "special:discord silent",
    float = false,
})

-- >> YOUTUBE MUSIC (Web App)  
hl.window_rule({
    name = "webapp-ytmusic",
    match = {
        class = "^(.*-music.youtube.com__-Default)$",
    },
    workspace = "special:ytmusic silent",
    float = false,
})

-- >> WHATSAPP (Web App)
hl.window_rule({
    name = "webapp-whatsapp",
    match = {
        class = "^(.*-web.whatsapp.com__-Default)$",
    },
    workspace = "special:whatsapp silent",
    float = false,
})

hl.window_rule({
    name = "game-launchers",
    match = {
        class = "^(heroic|net.lutris.Lutris)$",
    },
    workspace = "5 silent",
})

hl.window_rule({
    name = "lutris-others",
    match = {
        class = "^(net.lutris.Lutris)$",
    },
    float = true,
})

hl.window_rule({
    name = "lutris-main",
    match = {
        class = "^(net.lutris.Lutris)$",
        initial_title = "^(Lutris)$",
    },
    float = false,
})

-- >> JUEGOS EN EJECUCIÓN  
-- Juegos de Steam, Proton, CS2 o Wine  
hl.window_rule({
    name = "running-games-1",
    match = {
        class = "^(steam_app_.*|steam_proton|cs2|gamescope|epicgameslauncher.exe)$",
    },
    --match:class = ^(steam_app_.*|steam_proton|cs2|gamescope|epicgameslauncher.exe)$  
    render_unfocused = true,
    workspace = "6 silent",
})

hl.window_rule({
    name = "running-games-2",
    match = {
        xdg_tag = "^(proton-game)$",
    },
    render_unfocused = true,
    workspace = "6 silent",
})

hl.window_rule({
    name = "running-games-3",
    match = {
        content = 3,
    },
    render_unfocused = true,
    workspace = "6 silent",
})

-- steam (para ventanas de propiedades de juegos)
hl.window_rule({
    name = "steam-game-config",
    match = {
        class = "^(steam)",
    },
    workspace = "5 silent",
    float = true,
})

hl.window_rule({
    name = "steam-game-config",
    match = {
        class = "^(steam)$",
        initial_title = "^(Steam Big Picture Mode)$",
    },
    workspace = "5",
    float = true,
})

-- >> STEAM (Cliente Principal)  
-- Enviar la ventana principal al Workspace 5 y evitar que flote  
hl.window_rule({
    name = "steam-main",
    match = {
        class = "^(steam)$",
        title = "^(Steam)$",
    },
    workspace = "5 silent",
    float = false,
})

-- xwaylandvideobridge
hl.window_rule({
    name = "xwaylandvideobridge",
    match = {
        class = "^(xwaylandvideobridge)$",
    },
    workspace = "special:xwaylandvideobridge silent",
    float = false,
})


-- Reglas para el Video Peek (wl-mirror)
-- TODO: manual review — top-level key 'windowrulev = float, title:^(hypr_video_peek)$' has no enclosing section
-- TODO: manual review — top-level key 'windowrulev = center, title:^(hypr_video_peek)$' has no enclosing section
-- TODO: manual review — top-level key 'windowrulev = size 960 540, title:^(hypr_video_peek)$' has no enclosing section
-- TODO: manual review — top-level key 'windowrulev = sticky, title:^(hypr_video_peek)$' has no enclosing section
-- TODO: manual review — top-level key 'windowrulev = pin, title:^(hypr_video_peek)$' has no enclosing section
-- TODO: manual review — top-level key 'windowrulev = bordercolor rgb(ff0000), title:^(hypr_video_peek)$' has no enclosing section

