# Colors  
background = 0xFF181825  
base = 0xFF1E1E2E  
text = 0xFFCDD6F4  
alternate_base = 0xFF313244  
bright_text = 0xFFF5E0DC  
accent = 0xFFFAB387  
accent_secondary = 0xFFD65D0E  
  
# Font Sizes  
h1_size = 19  
h2_size = 15  
h3_size = 13  
font_size = 11  
small_font_size = 10  
  
# Other  
icon_theme = ""
