# Wayland
--enable-features=WaylandWindowDecorations
--ozone-platform=wayland

--disable-gpu-vsync
#--disable-frame-rate-limit

# X11
#--ozone-platform=x11

# keyring
--password-store=kwallet6

# test
--process-per-site
