device {
    name = logitech-usb-keyboard
    kb_layout = es
}

# Sunshine keyboard
device {
    name = keyboard-passthrough
    kb_layout = es
}

device {
    name = wireless-controller-touchpad
    enabled = false
}
