# -- LAYERRULES ---
layerrule {
    name = rofi
    match:namespace = rofi

    no_screen_share = $streamer_mode
}

layerrule {
    name = swaync-control-center
    match:namespace = swaync-control-center

    no_screen_share = $streamer_mode
}

layerrule {
    name = swaync-notification
    match:namespace = swaync-notification-window

    no_screen_share = $streamer_mode
}

