#!/usr/bin/env python3
import argparse
import re
import sys

# Mapping Equalizer APO filter identifiers to PipeWire builtin biquad labels
FILTER_MAP = {
    'PK': 'bq_peaking',
    'PEAK': 'bq_peaking',
    'LSC': 'bq_lowshelf',
    'LOW_SHELF': 'bq_lowshelf',
    'HSC': 'bq_highshelf',
    'HIGH_SHELF': 'bq_highshelf',
    'HP': 'bq_highpass',
    'HPF': 'bq_highpass',
    'LP': 'bq_lowpass',
    'LPF': 'bq_lowpass',
}

def parse_apo_line(line):
    # Matches formats like: Filter 1: ON PK Fc 32 Hz Gain 11.4 dB Q 1.504
    pattern = re.compile(
        r'Filter\s+\d+:\s*(?:ON|OFF)?\s*([A-Z_]+)\s+Fc\s+([\d\.]+)\s*(?:Hz)?\s*(?:Gain\s+([\-\d\.]+)\s*(?:dB)?)?\s*(?:Q\s+([\d\.]+))?',
        re.IGNORECASE
    )
    match = pattern.search(line)
    if not match:
        return None

    ftype, fc, gain, q = match.groups()
    ftype = ftype.upper()
    if ftype not in FILTER_MAP:
        return None

    return {
        'label': FILTER_MAP[ftype],
        'freq': float(fc),
        'gain': float(gain) if gain is not None else 0.0,
        'q': float(q) if q is not None else 0.707
    }

def generate_graph(filters):
    if not filters:
        return "{ nodes = [] links = [] inputs = [] outputs = [] }"

    nodes_lines = []
    # Left channel nodes
    for i, f in enumerate(filters, 1):
        if 'shelf' in f['label'] or 'peaking' in f['label']:
            ctrl = f'"Freq" = {f["freq"]} "Q" = {f["q"]} "Gain" = {f["gain"]}'
        else:
            ctrl = f'"Freq" = {f["freq"]} "Q" = {f["q"]}'
        nodes_lines.append(f'        {{ type = builtin name = eq_l_{i} label = {f["label"]} control = {{ {ctrl} }} }}')

    # Right channel nodes
    for i, f in enumerate(filters, 1):
        if 'shelf' in f['label'] or 'peaking' in f['label']:
            ctrl = f'"Freq" = {f["freq"]} "Q" = {f["q"]} "Gain" = {f["gain"]}'
        else:
            ctrl = f'"Freq" = {f["freq"]} "Q" = {f["q"]}'
        nodes_lines.append(f'        {{ type = builtin name = eq_r_{i} label = {f["label"]} control = {{ {ctrl} }} }}')

    links_lines = []
    total = len(filters)
    # Left links
    for i in range(1, total):
        links_lines.append(f'        {{ output = "eq_l_{i}:Out" input = "eq_l_{i+1}:In" }}')
    # Right links
    for i in range(1, total):
        links_lines.append(f'        {{ output = "eq_r_{i}:Out" input = "eq_r_{i+1}:In" }}')

    out = "{\n"
    out += "    nodes = [\n" + "\n".join(nodes_lines) + "\n    ]\n"
    out += "    links = [\n" + "\n".join(links_lines) + "\n    ]\n"
    out += f'    inputs  = [ "eq_l_1:In" "eq_r_1:In" ]\n'
    out += f'    outputs = [ "eq_l_{total}:Out" "eq_r_{total}:Out" ]\n'
    out += "}"
    return out

def indent(text, spaces):
    pad = ' ' * spaces
    return "\n".join(pad + line if line else line for line in text.split("\n"))


def generate_module(graph, sink_name, description, target):
    """Wrap the graph in a full filter-chain module.

    SPA JSON has no include directive, so a bare graph object is not a valid
    PipeWire drop-in on its own: it must be embedded in the module that uses it.
    """
    target_line = f'                target.object   = "{target}"\n' if target else ''
    return (
        "# Generated by APO_to_pipewire.py -- do not edit by hand.\n"
        "context.modules = [\n"
        "    { name = libpipewire-module-filter-chain\n"
        "        args = {\n"
        f'            node.description = "{description}"\n'
        f'            media.name       = "{description}"\n'
        "            capture.props = {\n"
        f'                node.name   = "{sink_name}"\n'
        "                media.class = \"Audio/Sink\"\n"
        "                audio.position = [ FL FR ]\n"
        "            }\n"
        "            playback.props = {\n"
        f'                node.name       = "{sink_name}_playback"\n'
        "                node.passive    = true\n"
        f"{target_line}"
        "            }\n"
        "            audio.channels = 2\n"
        "            audio.position = [ FL FR ]\n"
        "            filter.graph = " + indent(graph, 12).lstrip() + "\n"
        "        }\n"
        "    }\n"
        "]\n"
    )


def parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Convert an Equalizer APO preset into a PipeWire filter-chain config.")
    parser.add_argument('input_file', help="Equalizer APO preset (text)")
    parser.add_argument('output_file', nargs='?', default="headset-eq-graph.conf",
                        help="destination file (default: headset-eq-graph.conf)")
    parser.add_argument('--wrap', action='store_true',
                        help="emit a complete filter-chain module drop-in instead of a bare graph")
    parser.add_argument('--sink-name', default="sink_auriculares",
                        help="node.name of the created sink (--wrap only)")
    parser.add_argument('--description', default="Auriculares (EQ DSP)",
                        help="node.description of the created sink (--wrap only)")
    parser.add_argument('--target', default="",
                        help="target.object the sink plays back to (--wrap only)")
    return parser.parse_args(argv)


def main():
    args = parse_args(sys.argv[1:])

    filters = []
    try:
        with open(args.input_file, 'r', encoding='utf-8') as f:
            for line in f:
                parsed = parse_apo_line(line.strip())
                if parsed:
                    filters.append(parsed)
    except OSError as err:
        sys.exit(f"error: cannot read {args.input_file}: {err}")

    if not filters:
        sys.exit(f"error: no usable APO filter lines found in {args.input_file}")

    content = generate_graph(filters)
    if args.wrap:
        content = generate_module(content, args.sink_name, args.description, args.target)

    try:
        with open(args.output_file, 'w', encoding='utf-8') as f:
            f.write(content)
    except OSError as err:
        sys.exit(f"error: cannot write {args.output_file}: {err}")

    print(f"Generated DSP graph with {len(filters)} stereo bands -> {args.output_file}")

if __name__ == "__main__":
    main()
