[preferred]
default=hyprland;kde;gtk
org.freedesktop.impl.portal.FileChooser=kde
org.freedesktop.impl.portal.Settings=kde;hyprland
org.freedesktop.impl.portal.AppChooser=hyprland
org.freedesktop.impl.portal.Notification=hyprland
org.freedesktop.impl.portal.Secret=kde

org.freedesktop.impl.portal.Screenshot=hyprland
org.freedesktop.impl.portal.ScreenCast=hyprland
